worker-threads: 4
worker-fs-threads: 2
logger-level: info

is-testing: false

server-port: 8080

# Docker environment database connection
pg-connection: postgresql://testsuite:testsuite@postgres:5432/social_net_service_db_1
