components_manager:
    task_processors:                  # Task processor is an executor for coroutine tasks

        main-task-processor:          # Make a task processor for CPU-bound coroutine tasks.
            worker_threads: $worker-threads         # Process tasks in 4 threads.

        fs-task-processor:            # Make a separate task processor for filesystem bound tasks.
            worker_threads: $worker-fs-threads

    default_task_processor: main-task-processor

    components:                       # Configuring components that were registered via component_list
        server:
            listener:                 # configuring the main listening socket...
                port: $server-port            # ...to listen on this port and...
                task_processor: main-task-processor    # ...process incoming requests on this task processor.

        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    file_path: '@stderr'
                    level: $logger-level
                    overflow_behavior: discard  # Drop logs if the system is too busy to write them down.

        # Dynamic config options. Cache is disabled, updates are disabled.
        dynamic-config:
            # For most of userver dynamic configs, defaults are used, some are overridden here.
            # See userver "dynamic config" docs for what configs exist.
            defaults:
                HTTP_CLIENT_CONNECTION_POOL_SIZE: 1000
                POSTGRES_DEFAULT_COMMAND_CONTROL:
                    network_timeout_ms: 750
                    statement_timeout_ms: 500

        testsuite-support: {}

        congestion-control:
            load-enabled: false

        http-client:
        http-client-core:
            load-enabled: $is_testing
            fs-task-processor: fs-task-processor

        dns-client:
            fs-task-processor: fs-task-processor

        tests-control:
            load-enabled: $is-testing
            path: /tests/{action}
            method: POST
            task_processor: main-task-processor

        handler-ping:
            path: /ping
            method: GET
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match

        handler-login:
            path: /login
            method: POST
            task_processor: main-task-processor

        handler-user-register:
            path: /user/register
            method: POST
            task_processor: main-task-processor

        handler-user-get:
          path: /user/get/*
          method: GET
          task_processor: main-task-processor
          auth:
            types:
              - bearer
            scopes:
              - read

        handler-user-search:
          path: /user/search/*
          method: GET
          task_processor: main-task-processor
          auth:
            types:
              - bearer
            scopes:
              - read

        handler-friend-add:
          path: /friend/add/*
          method: PUT
          task_processor: main-task-processor
          auth:
            types:
              - bearer
            scopes:
              - read

        handler-friend-delete:
          path: /friend/delete/*
          method: PUT
          task_processor: main-task-processor
          auth:
            types:
              - bearer
            scopes:
              - read

        handler-post-create:
          path: /post/create
          method: POST
          task_processor: main-task-processor
          auth:
            types:
              - bearer
            scopes:
              - read

        handler-post-update:
          path: /post/update
          method: PUT
          task_processor: main-task-processor
          auth:
            types:
              - bearer
            scopes:
              - read

        handler-post-delete:
          path: /post/delete/*
          method: PUT
          task_processor: main-task-processor
          auth:
            types:
              - bearer
            scopes:
              - read

        handler-post-get:
          path: /post/get/*
          method: GET
          task_processor: main-task-processor

        handler-post-feed:
          path: /post/feed
          method: GET
          task_processor: main-task-processor
          auth:
            types:
              - bearer
            scopes:
              - read

        post-feed-cache: {}

        secdist: {}
        default-secdist-provider:
            config: $secdist-path
            missing-ok: true
            environment-secrets-key: SECDIST_CONFIG

        key-value-database:
            groups:
              - config_name: feed-redis
                db: feed-redis
                sharding_strategy: RedisStandalone
                allow_reads_from_master: true
            subscribe_groups: []
            thread_pools:
                redis_thread_pool_size: 4
                sentinel_thread_pool_size: 1

        postgres-db-1:
            dbconnection: $pg-connection
            dbconnection#env: DB_CONNECTION
            blocking_task_processor: fs-task-processor
            dns_resolver: async
            sync-start: true
            connlimit_mode: manual

        auth-pg-cache:
            pgcomponent: postgres-db-1
            update-interval: 10s